-- Product names, prices and author terms from Control de Ventas de Comics.xlsx,
-- Control de Ventas!B8:K44. Historical stock and sales are deliberately excluded.
CREATE TABLE sales_products (
 id TEXT PRIMARY KEY, title TEXT NOT NULL,
 category TEXT NOT NULL CHECK(category IN ('comic','merchandise','other')),
 cover TEXT NOT NULL DEFAULT '', price INTEGER NOT NULL CHECK(price >= 0),
 author TEXT NOT NULL DEFAULT '', author_percent INTEGER NOT NULL DEFAULT 0 CHECK(author_percent BETWEEN 0 AND 100),
 catalog_id TEXT UNIQUE, archived INTEGER NOT NULL DEFAULT 0 CHECK(archived IN (0,1)),
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-001','A la deriva con mi perro','comic','/series/a-la-deriva-con-mi-perro/cover/A%20LA%20DERIVA%20CON%20MI%20PERRO%20DEF_001%20cover%20copia.jpg',30000,'Tonypan',60,'a-la-deriva-con-mi-perro');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-002','Baká: El Mito Asesino','comic','/series/baka-el-mito-asesino/cover/Baka%20El%20mito%20Asesino%20Vol.1.jpg',60000,'Darwin Nuñez',80,'baka-el-mito-asesino');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-003','Bazuca - La heroína olvidada','comic','/series/bazuca-la-heroina-olvidada/cover/Bazuca%20Cover.jpg',15000,'Darwin Nuñez',80,'bazuca-la-heroina-olvidada');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-004','Cuentos del Magijara #1','comic','/series/cuentos-del-magijara/chapters/chapter-01/cover/Cuentos%20del%20Magijara%20%231%20Cover.jpg',15000,'Diego Colon',80,'cuentos-del-magijara::1');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-005','Cuentos del Magijara #2','comic','/series/cuentos-del-magijara/chapters/chapter-02/cover/Magijara%202%20Portadas.jpg',15000,'Diego Colon',80,'cuentos-del-magijara::2');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-006','Cuentos del Magijara #3','comic','/series/cuentos-del-magijara/chapters/chapter-03/cover/cover.jpg',15000,'Diego Colon',80,'cuentos-del-magijara::3');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-007','Cuentos del Magijara #4','comic','/series/cuentos-del-magijara/chapters/chapter-04/cover/magijara%20portada%20copia%204.jpg',15000,'Diego Colon',80,'cuentos-del-magijara::4');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-008','Cuentos del Magijara #5','comic','/series/cuentos-del-magijara/chapters/chapter-05/cover/cover.jpg',15000,'Diego Colon',80,'cuentos-del-magijara::5');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-009','How to Hide a Mermaid #1','comic','/series/how-to-hide-a-mermaid/chapters/chapter-01/cover/cover.jpg',15000,'Laura Perez',60,'how-to-hide-a-mermaid::1');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-010','How to Hide a Mermaid #2','comic','/series/how-to-hide-a-mermaid/chapters/chapter-02/cover/cover.jpg',15000,'Laura Perez',60,'how-to-hide-a-mermaid::2');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-011','La Armadura de mi Hermano','comic','/series/la-armadura-de-mi-hermano/cover/La%20Armadura.jpg',30000,'Manuel Shoo',80,'la-armadura-de-mi-hermano');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-012','La Guagua Voladora','comic','/series/la-guagua-voladora/cover/La%20Guagua%20Voladora(1).jpg',30000,'Nicole Hernandez',80,'la-guagua-voladora');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-013','La Lu’ Interior','comic','/series/la-lu-interior/cover/Portada%20y%20Contraportada%20-%20copia.jpg',15000,'Nicole Hernandez',80,'la-lu-interior');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-014','Last Breath','comic','/series/last-breath/cover/Portada%20y%20Contraportada%20-%20copia.jpg',15000,'Spencer Liriano',80,'last-breath');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-015','Más Freak de lo Normal #1','comic','/series/mas-freak-de-lo-normal/chapters/chapter-01/cover/cover.jpg',15000,'Francisco Balbuena',80,'mas-freak-de-lo-normal::1');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-016','Más Freak de lo Normal #2','comic','/series/mas-freak-de-lo-normal/chapters/chapter-02/cover/cover.jpg',15000,'Francisco Balbuena',80,'mas-freak-de-lo-normal::2');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-017','Más Freak de lo Normal #3','comic','/series/mas-freak-de-lo-normal/chapters/chapter-03/cover/cover.jpg',15000,'Francisco Balbuena',80,'mas-freak-de-lo-normal::3');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-018','Más Freak de lo Normal #4','comic','/series/mas-freak-de-lo-normal/chapters/chapter-04/cover/cover.jpg',15000,'Francisco Balbuena',80,'mas-freak-de-lo-normal::4');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-019','Más Freak de lo Normal #5','comic','/series/mas-freak-de-lo-normal/chapters/chapter-05/cover/cover.jpg',15000,'Francisco Balbuena',80,'mas-freak-de-lo-normal::5');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-020','Más Freak de lo Normal #6','comic','/series/mas-freak-de-lo-normal/chapters/chapter-06/cover/cover.jpg',15000,'Francisco Balbuena',80,'mas-freak-de-lo-normal::6');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-021','Más Freak de lo Normal Volumen. 1','comic','/series/mas-freak-de-lo-normal/cover/Copy%20of%20Freakier%20Than%20Normal%20Cover2.jpg',100000,'Francisco Balbuena',80,NULL);
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-022','Más Freak de lo Normal Volumen. 2','comic','/series/mas-freak-de-lo-normal/cover/Copy%20of%20Freakier%20Than%20Normal%20Cover2.jpg',100000,'Francisco Balbuena',80,NULL);
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-023','Mi Angelito Defectuoso #1','comic','/series/mi-angelito-defectuoso/chapters/chapter-01/cover/cover.jpg',15000,'Herlynn Sanchez',60,'mi-angelito-defectuoso::1');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-024','Pantaleta #1','comic','/series/pantaleta/chapters/chapter-01/cover/cover.jpg',15000,'Nicole Hernandez',80,'pantaleta::1');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-025','Pantaleta #2','comic','/series/pantaleta/cover/Pantaleta.jpg',15000,'Nicole Hernandez',80,'pantaleta::2');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-026','Quimica al 100% #1','comic','/series/quimica-al-100/chapters/chapter-01/cover/Quimica%20al%20100%20Chapter%201%20portada.jpg',15000,'Jose Cruz',80,'quimica-al-100::1');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-027','Quimica al 100% #2','comic','/series/quimica-al-100/chapters/chapter-02/cover/Quimica%20al%20100%20Chapter%202%20portada.jpg',15000,'Jose Cruz',80,'quimica-al-100::2');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-028','Quimica al 100% #3','comic','/series/quimica-al-100/chapters/chapter-03/cover/Quimica%20al%20100%20Chapter%203%20portada.jpg',15000,'Jose Cruz',80,'quimica-al-100::3');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-029','Ruptura','comic','/series/ruptura/cover/Ruptura.jpg',15000,'Maximo Montero',80,'ruptura');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-030','Sangrienta','comic','/series/sangrienta/cover/Baka%20%231%20Portada%20-%20copia.jpg',15000,'Francisco Balbuena',80,'sangrienta');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-031','Tomorrow Girl x Freakier Than Normal','comic','/series/tomorrow-girl-x-freakier-than-normal/cover/tomorrow%20girl%20x%20freakier%20than%20normal%20cover.jpg',15000,'Spencer Liriano',80,'tomorrow-girl-x-freakier-than-normal');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:LIB-032','Umbral, El reino de lo invisible','comic','/series/umbral-el-reino-de-lo-invisible/cover/portada%20umbral%20copia.jpg',15000,'Herlynn Sanchez',60,'umbral-el-reino-de-lo-invisible');
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:MER-001','Libro de colorear nati','merchandise','',30000,'Nathalia Rivera',80,NULL);
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:MER-002','Separadores','merchandise','',10000,'Nathalia Rivera',80,NULL);
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:MER-003','Llavetones','merchandise','',5000,'Patricia pachy',100,NULL);
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:MER-004','Mini Lllaveros','merchandise','',20000,'Patricia pachy',100,NULL);
INSERT INTO sales_products(id,title,category,cover,price,author,author_percent,catalog_id) VALUES ('product:MER-005','Botones','merchandise','',5000,'Anderson Feliz Encarnacion',100,NULL);
